apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8swrld
  region: us-east-1

nodeGroups:
  - name: nodegroup
    instanceType: t2.small
    desiredCapacity: 3
    volumeSize: 20
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']