---

apiVersion: v1
kind: Namespace
metadata:
  name: k8swrld-all

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8swrld-all
  name: deployment-k8swrld
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-k8swrld
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-k8swrld
    spec:
      containers:
      - image: {{ .Values.appImage }}
        imagePullPolicy: Always
        name: app-k8swrld
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: k8swrld-all
  name: service-k8swrld
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-k8swrld

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: k8swrld-all
  name: ingress-k8swrld
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-k8swrld
              port:
                number: 80
